server:
    port: 8081

spring:
    application:
        name: help-service

# config-server config
    config:
        import: "configserver:http://localhost:8888/"

app:
    message: Hello from Help Service Config Server
